### ISSUE TITLE
Als medewerker wil ik een andere medewerker tijdelijk kunnen autoriseren voor een losse zaak

### ISSUE THREAD

**Issue by MichelleDautzenberg** [GemeenteUtrecht/ZGW#408]
...zodat iemand aan mijn zaak kan werken of mijn zaak kan inzien in bijzondere situaties (bijv. bij Bezwaar, Ingebrekestelling).

Hoort bij EPIC #407

**Comment by sergei-maertens** [comment]
Ik denk dat we generiek wel kunnen werken met een `ObjectAutorisatie` concept:

```
ObjectAutorisatie:
    gebruiker: referentie naar gebruiker in applicatie
    object: url naar het object (zaak, informatieobject)
    van: datumtijd (optioneel, startdatum vanaf wanneer de autorisatie geldt)
    tot: datumtijd (optioneel, einddatum tot wanneer de autorisatie geldt)
```

Wat nog meegomen moet worden dan, is welke rollen/groepen van toepassing zijn voor permissies. Bijvoorbeeld mag inzien, maar niet bewerken o.i.d.
